# Generated by Django 5.1.2 on 2025-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqam')),
                ('language_code', models.CharField(choices=[('ru', '🇷🇺 Ruscha'), ('en', '🇺🇸 Inglizcha'), ('uz', "🇺🇿 O'zbekcha")], max_length=2, verbose_name='Til kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Botga a'zo bo'lgan sana sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Bot mijoz',
                'verbose_name_plural': 'Bot mijozlari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
